// Code generated by protoc-gen-go. DO NOT EDIT.
// source: practice_log.proto

package api

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Label struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId             string   `protobuf:"bytes,2,opt,name=parent_id,proto3" json:"parent_id,omitempty"`
	Children             []*Label `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Label) Reset()         { *m = Label{} }
func (m *Label) String() string { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()    {}
func (*Label) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1ba7d8d0866aa7c, []int{0}
}

func (m *Label) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Label.Unmarshal(m, b)
}
func (m *Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Label.Marshal(b, m, deterministic)
}
func (m *Label) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Label.Merge(m, src)
}
func (m *Label) XXX_Size() int {
	return xxx_messageInfo_Label.Size(m)
}
func (m *Label) XXX_DiscardUnknown() {
	xxx_messageInfo_Label.DiscardUnknown(m)
}

var xxx_messageInfo_Label proto.InternalMessageInfo

func (m *Label) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Label) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *Label) GetChildren() []*Label {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *Label) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PracticeLogEntry struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Labels               []string             `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	Duration             int32                `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Message              string               `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PracticeLogEntry) Reset()         { *m = PracticeLogEntry{} }
func (m *PracticeLogEntry) String() string { return proto.CompactTextString(m) }
func (*PracticeLogEntry) ProtoMessage()    {}
func (*PracticeLogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1ba7d8d0866aa7c, []int{1}
}

func (m *PracticeLogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PracticeLogEntry.Unmarshal(m, b)
}
func (m *PracticeLogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PracticeLogEntry.Marshal(b, m, deterministic)
}
func (m *PracticeLogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PracticeLogEntry.Merge(m, src)
}
func (m *PracticeLogEntry) XXX_Size() int {
	return xxx_messageInfo_PracticeLogEntry.Size(m)
}
func (m *PracticeLogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PracticeLogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PracticeLogEntry proto.InternalMessageInfo

func (m *PracticeLogEntry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PracticeLogEntry) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PracticeLogEntry) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *PracticeLogEntry) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *PracticeLogEntry) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *PracticeLogEntry) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Label)(nil), "api.Label")
	proto.RegisterType((*PracticeLogEntry)(nil), "api.PracticeLogEntry")
}

func init() { proto.RegisterFile("practice_log.proto", fileDescriptor_b1ba7d8d0866aa7c) }

var fileDescriptor_b1ba7d8d0866aa7c = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0xe9, 0xf6, 0x8f, 0xdb, 0x59, 0x10, 0xc9, 0x41, 0x42, 0x11, 0x2c, 0x7b, 0x90, 0x9e,
	0xb2, 0xb0, 0xbe, 0x81, 0xe0, 0x6d, 0x0f, 0x52, 0x3c, 0x79, 0x59, 0xa6, 0xcd, 0x58, 0x03, 0x6d,
	0x13, 0xd3, 0xf4, 0xe0, 0xab, 0xf9, 0x74, 0xd2, 0xb4, 0xdd, 0x3d, 0x78, 0xcb, 0xf7, 0x65, 0x32,
	0xbf, 0xf0, 0x03, 0x66, 0x2c, 0xd6, 0x4e, 0xd5, 0x74, 0x6e, 0x75, 0x23, 0x8c, 0xd5, 0x4e, 0xb3,
	0x10, 0x8d, 0xca, 0x1e, 0x1b, 0xad, 0x9b, 0x96, 0x0e, 0xbe, 0xaa, 0xc6, 0xcf, 0x83, 0x53, 0x1d,
	0x0d, 0x0e, 0x3b, 0x33, 0x4f, 0xed, 0xbf, 0x21, 0x3e, 0x61, 0x45, 0x2d, 0xbb, 0x85, 0x8d, 0x92,
	0x3c, 0xc8, 0x83, 0x22, 0x2d, 0x37, 0x4a, 0xb2, 0x07, 0x48, 0x0d, 0x5a, 0xea, 0xdd, 0x59, 0x49,
	0xbe, 0xf1, 0xf5, 0xb5, 0x60, 0x4f, 0xb0, 0xad, 0xbf, 0x54, 0x2b, 0x2d, 0xf5, 0x3c, 0xcc, 0xc3,
	0x62, 0x77, 0x04, 0x81, 0x46, 0x09, 0xbf, 0xab, 0xbc, 0xdc, 0x31, 0x06, 0x51, 0x8f, 0x1d, 0xf1,
	0xc8, 0x2f, 0xf0, 0xe7, 0xfd, 0x6f, 0x00, 0x77, 0x6f, 0xcb, 0x7f, 0x4f, 0xba, 0x79, 0xed, 0x9d,
	0xfd, 0xf9, 0x87, 0xe7, 0x70, 0x33, 0x0e, 0x64, 0xaf, 0xf0, 0x35, 0xb2, 0x7b, 0x48, 0xda, 0x89,
	0x32, 0x78, 0x70, 0x5a, 0x2e, 0x89, 0x65, 0xb0, 0x95, 0xa3, 0x45, 0xa7, 0x74, 0xef, 0x71, 0x71,
	0x79, 0xc9, 0x4c, 0x40, 0x24, 0xd1, 0x11, 0x8f, 0xf3, 0xa0, 0xd8, 0x1d, 0x33, 0x31, 0x5b, 0x11,
	0xab, 0x15, 0xf1, 0xbe, 0x5a, 0x29, 0xfd, 0xdc, 0x44, 0xef, 0x68, 0x18, 0xb0, 0x21, 0x9e, 0xcc,
	0xf4, 0x25, 0xbe, 0xc4, 0x1f, 0x93, 0xd7, 0x2a, 0xf1, 0x4f, 0x9f, 0xff, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x3e, 0x53, 0x9e, 0x72, 0x79, 0x01, 0x00, 0x00,
}
