package cmd

import "github.com/calvinfeng/playground/datastore"

var recordings = []*datastore.PracticeRecording{
	{
		RecordedYear:     2019,
		RecordedMonth:    10,
		RecordedDay:      4,
		YoutubeURL:       "https://www.youtube.com/watch?v=U4-0h6go0RA",
		VideoOrientation: "portrait",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    10,
		RecordedDay:      7,
		YoutubeURL:       "https://www.youtube.com/watch?v=fu_npFZMHkc",
		VideoOrientation: "portrait",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    10,
		RecordedDay:      23,
		YoutubeURL:       "https://www.youtube.com/watch?v=OeN2GGssoJ4",
		VideoOrientation: "portrait",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    10,
		RecordedDay:      26,
		YoutubeURL:       "https://www.youtube.com/watch?v=_mQIFluFuv8",
		VideoOrientation: "portrait",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      7,
		YoutubeURL:       "https://www.youtube.com/watch?v=AGhYB0QryhU",
		VideoOrientation: "portrait",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      9,
		YoutubeURL:       "https://www.youtube.com/watch?v=SWWCfI0Qavc",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      9,
		YoutubeURL:       "https://www.youtube.com/watch?v=-_nJNU8sXOc",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      17,
		YoutubeURL:       "https://www.youtube.com/watch?v=w9VWkEnjH8o",
		VideoOrientation: "portrait",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      17,
		YoutubeURL:       "https://www.youtube.com/watch?v=0-2C1Z9Qwqg",
		VideoOrientation: "portrait",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      20,
		YoutubeURL:       "https://www.youtube.com/watch?v=rcOqJuiFrQM",
		VideoOrientation: "portrait",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      26,
		YoutubeURL:       "https://www.youtube.com/watch?v=J3sxA_JeyBo",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    12,
		RecordedDay:      29,
		YoutubeURL:       "https://www.youtube.com/watch?v=emjmvfMPtqs",
		VideoOrientation: "portrait",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      4,
		YoutubeURL:       "https://www.youtube.com/watch?v=tLh_cBTHLOY",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      8,
		YoutubeURL:       "https://www.youtube.com/watch?v=qmrl3do41lo",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      5,
		YoutubeURL:       "https://www.youtube.com/watch?v=4W1_zKsl7wE",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      25,
		YoutubeURL:       "https://www.youtube.com/watch?v=XZ2zg1Nww5U",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      26,
		YoutubeURL:       "https://www.youtube.com/watch?v=FKmWPsknfuc",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      2,
		YoutubeURL:       "https://www.youtube.com/watch?v=tfJ4ou280js",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      14,
		YoutubeURL:       "https://www.youtube.com/watch?v=Nkoxd0XPgyk",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      15,
		YoutubeURL:       "https://www.youtube.com/watch?v=a0tmaY6MabQ",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      24,
		YoutubeURL:       "https://www.youtube.com/watch?v=Jn9K7wxdAeA",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      29,
		YoutubeURL:       "https://www.youtube.com/watch?v=uJYoKvneN88",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      6,
		YoutubeURL:       "https://www.youtube.com/watch?v=Dogm9asWlRY",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      14,
		YoutubeURL:       "https://www.youtube.com/watch?v=3zEoEEIkUAw",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      14,
		YoutubeURL:       "https://www.youtube.com/watch?v=IXeOGHn9hSQ",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      24,
		YoutubeURL:       "https://www.youtube.com/watch?v=MkGWwgaejE4",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      30,
		YoutubeURL:       "https://www.youtube.com/watch?v=7DUoqQkeXG0",
		VideoOrientation: "landscape",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    4,
		RecordedDay:      9,
		YoutubeURL:       "https://www.youtube.com/watch?v=ifYsuZX9sOQ",
		VideoOrientation: "portrait",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    4,
		RecordedDay:      10,
		YoutubeURL:       "https://www.youtube.com/watch?v=DKDFRyKTXIU",
		VideoOrientation: "portrait",
	},
}
