package cmd

import "github.com/calvinfeng/playground/datastore"

var recordings = []*datastore.PracticeRecording{
	{
		RecordedYear:     2019,
		RecordedMonth:    9,
		RecordedDay:      24,
		YouTubeVideoID:   "tjxsubPb_3A",
		VideoOrientation: "landscape",
		Title:            "Monthly Progress Recording 001",
		IsProgressReport: 1,
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    10,
		RecordedDay:      4,
		YouTubeVideoID:   "U4-0h6go0RA",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Wonderful Tonight",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    10,
		RecordedDay:      7,
		YouTubeVideoID:   "fu_npFZMHkc",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Wonderful Tonight",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    10,
		RecordedDay:      23,
		YouTubeVideoID:   "OeN2GGssoJ4",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Perfect",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    10,
		RecordedDay:      26,
		YouTubeVideoID:   "_mQIFluFuv8",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Now & Forever",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      7,
		YouTubeVideoID:   "AGhYB0QryhU",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - 21 Guns",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      9,
		YouTubeVideoID:   "SWWCfI0Qavc",
		VideoOrientation: "landscape",
		Title:            "Fetch Band Session - 21 Guns",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      9,
		YouTubeVideoID:   "-_nJNU8sXOc",
		VideoOrientation: "landscape",
		Title:            "Fetch Band Session - 海闊天空",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      11,
		YouTubeVideoID:   "XDyRzfTAsBI",
		VideoOrientation: "landscape",
		Title:            "Monthly Progress Recording 002",
		IsProgressReport: 1,
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      17,
		YouTubeVideoID:   "w9VWkEnjH8o",
		VideoOrientation: "portrait",
		Title:            "Fetch Band Session - Wonderful Tonight",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      17,
		YouTubeVideoID:   "0-2C1Z9Qwqg",
		VideoOrientation: "portrait",
		Title:            "Fetch Band Session - 21 Guns",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      20,
		YouTubeVideoID:   "rcOqJuiFrQM",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Wonderful Tonight",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      26,
		YouTubeVideoID:   "J3sxA_JeyBo",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - 21 Guns Solo",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      27,
		YouTubeVideoID:   "u2TNvnlBhy0",
		VideoOrientation: "landscape",
		Title:            "Monthly Progress Recording 003",
		IsProgressReport: 1,
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    12,
		RecordedDay:      29,
		YouTubeVideoID:   "emjmvfMPtqs",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Perfect Solo",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      1,
		YouTubeVideoID:   "H_qs9Mpl2ek",
		VideoOrientation: "landscape",
		Title:            "Monthly Progress Recording 004",
		IsProgressReport: 1,
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      4,
		YouTubeVideoID:   "tLh_cBTHLOY",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Wonderful Tonight",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      5,
		YouTubeVideoID:   "4W1_zKsl7wE",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Now & Forever",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      8,
		YouTubeVideoID:   "qmrl3do41lo",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Perfect",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      25,
		YouTubeVideoID:   "XZ2zg1Nww5U",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - 21 Guns Take 1",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      26,
		YouTubeVideoID:   "FKmWPsknfuc",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - 21 Guns Take 2",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      2,
		YouTubeVideoID:   "tfJ4ou280js",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Perfect",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      9,
		YouTubeVideoID:   "WdLsPuKwA1E",
		VideoOrientation: "landscape",
		Title:            "Monthly Progress Recording 005 - 21 Guns (w/ Steve)",
		IsProgressReport: 1,
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      14,
		YouTubeVideoID:   "Nkoxd0XPgyk",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Wonderful Tonight",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      15,
		YouTubeVideoID:   "a0tmaY6MabQ",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Wonderful Tonight",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      24,
		YouTubeVideoID:   "Jn9K7wxdAeA",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - 21 Guns Take 3",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      24,
		YouTubeVideoID:   "fkttcMBj5BM",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Yesterday",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      29,
		YouTubeVideoID:   "uJYoKvneN88",
		VideoOrientation: "landscape",
		Title:            "Fetch Band Session - Back in Black 1st Attempt",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      6,
		YouTubeVideoID:   "Dogm9asWlRY",
		VideoOrientation: "landscape",
		Title:            "Fetch Band Session - Back in Black 2nd Attempt",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      14,
		YouTubeVideoID:   "3zEoEEIkUAw",
		VideoOrientation: "landscape",
		Title:            "Fetch Band Session - Back in Black 3rd Attempt at 95 BPM",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      14,
		YouTubeVideoID:   "IXeOGHn9hSQ",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Back in Black",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      21,
		YouTubeVideoID:   "EYWBd7iS2A0",
		VideoOrientation: "landscape",
		Title:            "Monthly Progress Recording 006 - Yesterday",
		IsProgressReport: 1,
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      24,
		YouTubeVideoID:   "MkGWwgaejE4",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Back in Black",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      30,
		YouTubeVideoID:   "7DUoqQkeXG0",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Back in Black",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    4,
		RecordedDay:      9,
		YouTubeVideoID:   "ifYsuZX9sOQ",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Back in Black Solo 70% Speed",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    4,
		RecordedDay:      10,
		YouTubeVideoID:   "DKDFRyKTXIU",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Back in Black Solo 80% Speed",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    4,
		RecordedDay:      15,
		YouTubeVideoID:   "8TvQOgy0C-Y",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - 不再犹豫",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    4,
		RecordedDay:      20,
		YouTubeVideoID:   "esnvUHSC8-Y",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Back in Black Solo 100% Speed",
	},
}
