package cmd

import "github.com/calvinfeng/playground/datastore"

var recordings = []*datastore.PracticeRecording{
	{
		RecordedYear:     2019,
		RecordedMonth:    10,
		RecordedDay:      4,
		YoutubeURL:       "https://www.youtube.com/watch?v=U4-0h6go0RA",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Wonderful Tonight",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    10,
		RecordedDay:      7,
		YoutubeURL:       "https://www.youtube.com/watch?v=fu_npFZMHkc",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Wonderful Tonight",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    10,
		RecordedDay:      23,
		YoutubeURL:       "https://www.youtube.com/watch?v=OeN2GGssoJ4",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Perfect",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    10,
		RecordedDay:      26,
		YoutubeURL:       "https://www.youtube.com/watch?v=_mQIFluFuv8",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Now & Forever",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      7,
		YoutubeURL:       "https://www.youtube.com/watch?v=AGhYB0QryhU",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - 21 Guns",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      9,
		YoutubeURL:       "https://www.youtube.com/watch?v=SWWCfI0Qavc",
		VideoOrientation: "landscape",
		Title:            "Fetch Band Session - 21 Guns",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      9,
		YoutubeURL:       "https://www.youtube.com/watch?v=-_nJNU8sXOc",
		VideoOrientation: "landscape",
		Title:            "Fetch Band Session - 海闊天空",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      17,
		YoutubeURL:       "https://www.youtube.com/watch?v=w9VWkEnjH8o",
		VideoOrientation: "portrait",
		Title:            "Fetch Band Session - Wonderful Tonight",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      17,
		YoutubeURL:       "https://www.youtube.com/watch?v=0-2C1Z9Qwqg",
		VideoOrientation: "portrait",
		Title:            "Fetch Band Session - 21 Guns",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      20,
		YoutubeURL:       "https://www.youtube.com/watch?v=rcOqJuiFrQM",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Wonderful Tonight",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    11,
		RecordedDay:      26,
		YoutubeURL:       "https://www.youtube.com/watch?v=J3sxA_JeyBo",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - 21 Guns Solo",
	},
	{
		RecordedYear:     2019,
		RecordedMonth:    12,
		RecordedDay:      29,
		YoutubeURL:       "https://www.youtube.com/watch?v=emjmvfMPtqs",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Perfect Solo",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      4,
		YoutubeURL:       "https://www.youtube.com/watch?v=tLh_cBTHLOY",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Wonderful Tonight",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      8,
		YoutubeURL:       "https://www.youtube.com/watch?v=qmrl3do41lo",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Perfect",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      5,
		YoutubeURL:       "https://www.youtube.com/watch?v=4W1_zKsl7wE",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Now & Forever",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      25,
		YoutubeURL:       "https://www.youtube.com/watch?v=XZ2zg1Nww5U",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - 21 Guns Take 1",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    1,
		RecordedDay:      26,
		YoutubeURL:       "https://www.youtube.com/watch?v=FKmWPsknfuc",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - 21 Guns Take 2",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      2,
		YoutubeURL:       "https://www.youtube.com/watch?v=tfJ4ou280js",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Perfect",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      14,
		YoutubeURL:       "https://www.youtube.com/watch?v=Nkoxd0XPgyk",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Wonderful Tonight",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      15,
		YoutubeURL:       "https://www.youtube.com/watch?v=a0tmaY6MabQ",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Wonderful Tonight",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      24,
		YoutubeURL:       "https://www.youtube.com/watch?v=Jn9K7wxdAeA",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - 21 Guns Take 3",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      24,
		YoutubeURL:       "https://www.youtube.com/watch?v=fkttcMBj5BM",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Yesterday",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    2,
		RecordedDay:      29,
		YoutubeURL:       "https://www.youtube.com/watch?v=uJYoKvneN88",
		VideoOrientation: "landscape",
		Title:            "Fetch Band Session - Back in Black 1st Attempt",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      6,
		YoutubeURL:       "https://www.youtube.com/watch?v=Dogm9asWlRY",
		VideoOrientation: "landscape",
		Title:            "Fetch Band Session - Back in Black 2nd Attempt",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      14,
		YoutubeURL:       "https://www.youtube.com/watch?v=3zEoEEIkUAw",
		VideoOrientation: "landscape",
		Title:            "Fetch Band Session - Back in Black 3rd Attempt at 95 BPM",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      14,
		YoutubeURL:       "https://www.youtube.com/watch?v=IXeOGHn9hSQ",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Back in Black",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      24,
		YoutubeURL:       "https://www.youtube.com/watch?v=MkGWwgaejE4",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Back in Black",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    3,
		RecordedDay:      30,
		YoutubeURL:       "https://www.youtube.com/watch?v=7DUoqQkeXG0",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Back in Black",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    4,
		RecordedDay:      9,
		YoutubeURL:       "https://www.youtube.com/watch?v=ifYsuZX9sOQ",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Back in Black Solo 70% Speed",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    4,
		RecordedDay:      10,
		YoutubeURL:       "https://www.youtube.com/watch?v=DKDFRyKTXIU",
		VideoOrientation: "portrait",
		Title:            "Practice Recording - Back in Black Solo 80% Speed",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    4,
		RecordedDay:      15,
		YoutubeURL:       "https://www.youtube.com/watch?v=8TvQOgy0C-Y",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - 不再犹豫",
	},
	{
		RecordedYear:     2020,
		RecordedMonth:    4,
		RecordedDay:      20,
		YoutubeURL:       "https://www.youtube.com/watch?v=esnvUHSC8-Y",
		VideoOrientation: "landscape",
		Title:            "Practice Recording - Back in Black Solo 100% Speed",
	},
}
